services:
  dev:
    build: .
    volumes:
      - .:/app
      - ./music:/mnt/music
    env_file:
      - ./.env.dev
    command: npm run dev
    profiles: ["dev"]

  test:
    build: .
    command: npm run test
    profiles: ["test"]

  test-coverage:
    build: .
    command: npm run test:coverage
    profiles: ["coverage"]

  lint:
    build: .
    command: npm run lint
    profiles: ["lint"]

  prod:
    build: .
    command: bash -c "npm run build ; npm run start"
    env_file:
      - ./.env.proda
    profiles: ["prod"]

  db:
    hostname: db
    image: postgres:16
    env_file:
      - ./.env.db
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    profiles: ["prod", "dev"]
