services:
  dev:
    build:
      context: .
      target: dev
    volumes:
      - .:/lebot2.zz
      - music_data:/lebot2.zz/music
    env_file:
      - ./.env.dev
    profiles: ["dev"] 

  test:
    build:
      context: .
      target: dev
    volumes:
      - .:/lebot2.zz
    command: npm run test
    profiles: ["test"]
    
  test-coverage:
    build:
      context: .
      target: dev
    volumes:
      - .:/lebot2.zz
    command: npm run test:coverage
    profiles: ["coverage"]

  lint:
    build:
      context: .
      target: dev
    volumes:
      - .:/lebot2.zz
    command: npm run lint
    profiles: ["lint"]

  prod:
    image: lamenace2zz/lebot2zz:latest
    env_file:
      - ./.env.prod
    volumes:
      - music_data:/lebot2.zz/music
    profiles: ["prod"]

  db:
    hostname: db
    image: postgres:16
    env_file:
      - ./.env.db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    profiles: ["prod", "dev"]

volumes:
  db_data:
  music_data:
